### ISSUE TITLE
Replace nodenv, rbenv, nvm, rvm et al with asdf-vm

### ISSUE THREAD

**Issue by kmayer** [carbonfive/seed-crystal#1]
It purports to be an all-in-one solution.

https://asdf-vm.com

**Comment by kmayer** [comment]
Switching to asdf-vm... is this the next thing? What do we want to recommend to our clients? That's what we should use internally.

**Comment by christiannelson** [comment]
@kmayer ASDF is meant to be a plugable handle-all-kinds-of-things version manager.

In my experience, it's missing some feature as compared to rbenv (what I use for ruby version). Specifically, it doesn't auto-rehash when changing versions. So, technically it can do it all, but at least for ruby, it doesn't do it as well. My experience is dated, so maybe this is not a thing anymore?

@mattbrictson tried it recently I think. Matt, any thoughts?

**Comment by christiannelson** [comment]
See https://github.com/asdf-vm/asdf-ruby/issues/63

**Comment by mattbrictson** [comment]
I was unhappy with asdf and eventually switched back to a combination of rbenv and nodenv. In my experience: 

* asdf was noticeably slower at invoking ruby (compared to rbenv)
* I had the re-shim issue @christiannelson linked above
* The nodejs plugin doesn't handle default-packages properly
* The java and maven plugins both have bugs that prevent JAVA_HOME from being set correctly

**Comment by mattbrictson** [comment]
rbenv and nodenv are very similar (nodenv is actually a fork of rbenv), which makes that combination nice. If you learn one of them you've basically learned both.
